export const initialState = {
    planets: [],
    isPlanetDataFetched: false,
    vehicles: [],
    isVehicleDataFetched: false,
    token: '',
    isFalconeFetched: false,
    falconePlanet: '',
    timeTaken: 0,
    startAgain: false,
    falconeData: [
      {
        label: 'Destination 1',
        planets: '',
        vehicles: '',
        selectedPlanet: '',
        selectedVehicle: '',
        time: 0,
      },
      {
        label: 'Destination 2',
        planets: '',
        vehicles: '',
        selectedPlanet: '',
        selectedVehicle: '',
        time: 0,
      },
      {
        label: 'Destination 3',
        planets: '',
        vehicles: '',
        selectedPlanet: '',
        selectedVehicle: '',
        time: 0,
      },
      {
        label: 'Destination 4',
        planets: '',
        vehicles: '',
        selectedPlanet: '',
        selectedVehicle: '',
        time: 0,
      },
    ]
  };